name: Build Linux Container Image and Push to ACR
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: worker.consumer.servicebus
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: pocservicebus.azurecr.io
        username: pocservicebus
        password: noyoNfSx8hBwKKgCTTUe1qwZZyZx/Ofjc2MANHhzZv+ACRAAPm1
    - run: |
        docker build . -t pocservicebus.azurecr.io/workerservicebus:${{ github.sha }}
        docker push pocservicebus.azurecr.io/workerservicebus:${{ github.sha }}
